tasks:
  - name: npm
    init: npm install
    command: npm run dev
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5173
    onOpen: open-browser
  - port: 4173
    onOpen: open-preview
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
